"""Initial migration

Revision ID: 3e74ec0f32f5
Revises: 543bf66b9a26
Create Date: 2023-10-19 02:20:48.169085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e74ec0f32f5'
down_revision = '543bf66b9a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electro_scooter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('electro_scooter')
    # ### end Alembic commands ###
